export const genderCopy = {
  english: ['Men', 'Women'],
  spanish: ['Hombres', 'Mujeres'],
}
export const languageCopy = {
  english: ['English', 'Spanish'],
  spanish: ['Inglés', 'Española'],
}
export const foodServiceCopy = {
  english: [
    'Breakfast',
    'Bulk Foods',
    'Cal Fresh Application Assistance',
    'Dinner',
    'EBT',
    'Food Bank',
    'Grocery Vouchers',
    'Lunch',
    'Mobile Food Market',
    'Mobile Food Pantry',
    'Nutrition Services',
    'Senior Meal Site',
    'WIC',
  ],
  spanish: [
    'Alimentos a granel',
    'Almuerzo',
    'Asistencia con la solicitud de Cal Fresh',
    'Banco de comida',
    'Cena',
    'Desayuno',
    'Despensa móvil de alimentos',
    'EBT',
    'Mercado móvil de alimentos',
    'Servicios de nutrición',
    'Sitio de comidas para personas mayores',
    'Vales de comestibles',
    'WIC',
  ],
}
export const housingServiceCopy = {
  english: [
    'domestic violence shelter',
    'housing',
    'sober living homes',
    'transitional shelter',
  ],
  spanish: [
    'alojamiento',
    'hogares de vida sobria',
    'refugio de transición',
    'refugio de violencia doméstica',
  ],
}
export const clothingServiceCopy = {
  english: ['Clothing', 'Laundry', 'ThriftStore', 'ThriftStoreVouchers'],
  spanish: [
    'Ropa sucia',
    'Ropa',
    'Tienda de segunda mano',
    'Vales de tienda de segunda mano',
  ],
}
export const communitysupportServiceCopy = {
  english: [
    'Academic Assistance',
    'Adminstration & Enrollment',
    'Advocacy Services',
    'Animal Services',
    'Career Development',
    'Case Management',
    'Child Care Assistance',
    'Child Health & Disabilities',
    'College Advisement Services',
    'Couples Therapy',
    'Education',
    'Emergency Services',
    'Employment',
    'Family Therapy',
    'Financial Assistance',
    'General Support',
    'Haircuts',
    'Hygiene Products',
    'LGBTQ Services',
    'Mentorship',
    'Older Adult Services',
    'Parenting Education',
    'Public Defender',
    'Referrals',
    'Safe Parking',
    'Showers',
    'Sports',
    'Utility Financial Assistance',
    'Warming Center',
    'Youth',
    "Veteran's",
  ],
  spanish: [
    'Administración e inscripción',
    'Apoyo general',
    'Asistencia académica',
    'Asistencia financiera para servicios públicos',
    'Asistencia financiera',
    'Asistencia para el cuidado de niños',
    'Centro de calentamiento',
    'Cortes de pelo',
    'Defensor público',
    'Deportes',
    'Desarrollo de carrera',
    'Duchas',
    'Educación para padres',
    'Educación',
    'Empleo',
    'Estacionamiento seguro',
    'Gestión de casos',
    'Juventud',
    'Mentoría',
    'Productos de higiene',
    'Referencias',
    'Salud infantil y discapacidades',
    'Servicios de asesoramiento universitario',
    'Servicios de defensa',
    'Servicios de emergencia',
    'Servicios LGBTQ',
    'Servicios para adultos mayores',
    'Servicios para animales',
    'Terapia de pareja',
    'Terapia familiar',
    'Veteranos',
  ],
}
export const transportationServiceCopy = {
  english: [
    'Airport Transportation',
    'Bus',
    'Child Transportation',
    'Safe Parking',
    'Shuttle',
  ],
  spanish: [
    'Autobús',
    'Estacionamiento seguro',
    'Lanzadera',
    'Transporte al aeropuerto',
    'Transporte de niños',
  ],
}
export const medicalsupportServiceCopy = {
  english: [
    'Abortion',
    'AIDS',
    'Birth Control',
    'Breast Exam',
    'Dental',
    'Emergency Services',
    'Health Care Center',
    'HIV',
    'Immunization',
    'Medical Assistance',
    "Men's Health",
    'Mobile Health Services',
    'OBGYN Services',
    'Outpatient Medical Care',
    'Pediatrics',
    'Pharmacy',
    'Pregnancy',
    'Primary Care',
    'STD/STI',
    'Tuberculosis',
    'Vision',
    "Women's Health Services",
  ],
  spanish: [
    'Aborto',
    'Asistencia medica',
    'Atención médica ambulatoria',
    'Atención primaria',
    'Centro de salud',
    'Control de la natalidad',
    'Dental',
    'El embarazo',
    'ETS / ITS',
    'Exámen de senos',
    'Farmacia',
    'Inmunización',
    'Pediatría',
    'Salud de los hombres',
    'Servicios de emergencia',
    'Servicios de salud móviles',
    'Servicios de salud para mujeres',
    'Servicios OBGYN',
    'SIDA',
    'Tuberculosis',
    'VIH',
    'Visión',
  ],
}
export const mentalhealthServiceCopy = {
  english: [
    'Anger Management',
    'Behavioral Therapy',
    'Behavioral Wellness',
    'Case Management',
    'Counseling',
    'Couples Therapy',
    'Crisis Stabilization',
    'Emergency Services',
    'Family Therapy',
    'Group Therapy',
    'Mental Illness',
    'Psychiatry',
    'Social Security',
    'Social Services',
    'Youth Mental Health',
  ],
  spanish: [
    'Asesoramiento',
    'Bienestar conductual',
    'Control de la ira',
    'Enfermedad mental',
    'Estabilización de crisis',
    'Gestión de casos',
    'Psiquiatría',
    'Salud mental juvenil',
    'Seguridad Social',
    'Servicios de emergencia',
    'Servicios sociales',
    'Terapia de comportamiento',
    'Terapia de grupo',
    'Terapia de pareja',
    'Terapia familiar',
  ],
}
export const resourcedirectoryServiceCopy = {
  english: [
    'Academic Assistance',
    'Addiction Services',
    'Adminstration & Enrollement',
    'Advocacy',
    'Affordable Housing',
    'Animal Services',
    'Bankruptcy Clinic',
    'Birth Certificate',
    'Bulk Food',
    'Bus',
    'Career Development',
    'Childcare',
    'Counseling',
    'Dental',
    'Detox',
    'Documents',
    'Domestic Violence',
    'Drug and Alcohol Counseling',
    'Education',
    'Employment',
    'Family',
    'Financial',
    'General Support',
    'Haircuts',
    'Hygeine',
    'Immagration',
    'Laundry',
    'LGBTQ',
    'Outpatient Counseling',
    'Parenting',
    'Probation',
    'Public Defender',
    'Shelter',
    'Showers',
    'Social Security',
    'Temp Agency',
    'Thrift Store',
    "Veteran's",
    'Vision',
    'Youth',
  ],
  spanish: [
    'Abogacía',
    'Abrigo',
    'Administración e inscripción',
    'Agencia de trabajo temporal',
    'Alimentos a granel',
    'Apoyo general',
    'Asesoramiento para pacientes ambulatorios',
    'Asesoramiento sobre drogas y alcohol',
    'Asesoramiento',
    'Asistencia académica',
    'Autobús',
    'Certificado de nacimiento',
    'Clínica de quiebras',
    'Cortes de pelo',
    'Crianza de los hijos',
    'Cuidado de niños',
    'Defensor público',
    'Dental',
    'Desarrollo de carrera',
    'Desintoxicación',
    'Documentos',
    'Duchas',
    'Educación',
    'Empleo',
    'Familia',
    'Financiero',
    'Hygeine',
    'Inmagración',
    'Juventud',
    'LGBTQ',
    'Libertad condicional',
    'Ropa sucia',
    'Seguridad Social',
    'Servicios de adicción',
    'Servicios para animales',
    'Tienda de segunda mano',
    'Veteranos',
    'Violencia doméstica',
    'Visión',
    'Vivienda asequible',
  ],
}
export const socialservicesServiceCopy = {
  english: [
    'Addiction Services',
    'Advocacy Services',
    'Behavioral Therapy',
    'Behavioral Wellness',
    'Case Management',
    'Childcare',
    'Counseling',
    'Education',
    'Family',
    'Financial',
    'Housing Assistance',
    'Immigration Law',
    'Legal Assistance',
    'LGBTQ Services',
    'Medical Assistance',
    'Outpatient Counseling',
    'Pregnancy Services',
    'Shelter',
    "Veteran's",
    'Youth',
  ],
  spanish: [
    'Abrigo',
    'Asesoramiento para pacientes ambulatorios',
    'Asesoramiento',
    'Asistencia legal',
    'Asistencia medica',
    'Asistencia para la vivienda',
    'Bienestar conductual',
    'Cuidado de niños',
    'Educación',
    'Familia',
    'Financiero',
    'Gestión de casos',
    'Juventud',
    'Ley de inmigración',
    'Servicios de adicción',
    'Servicios de defensa',
    'Servicios de embarazo',
    'Servicios LGBTQ',
    'Terapia de comportamiento',
    'Veteranos',
  ],
}
export const legalservicesServiceCopy = {
  english: [
    'Bankruptcy Clinic',
    'Birth Certificate',
    'Documents',
    'DUI',
    'Immigration Law',
    'Legal Assistance',
    'Legal Resource Center',
    "Veteran's Legal Assistance",
  ],
  spanish: [
    'Asistencia jurídica para veteranos',
    'Asistencia legal',
    'Centro de recursos legales',
    'Certificado de nacimiento',
    'Clínica de quiebras',
    'Documentos',
    'DUI',
    'Ley de inmigración',
  ],
}
export const employmentServiceCopy = {
  english: ['Career Development', 'Employment', 'Temp Agency'],
  spanish: ['Agenciadetrabajotemporal', 'Desarrollodecarrera', 'Empleo'],
}
export const substanceuseServiceCopy = {
  english: [
    'Addiction Services',
    'Alcoholics Anonymous',
    'Crystal Meth Anonymous',
    'Detox Centers',
    'Drug and Alcohol Counseling',
    'DUI',
    'Narcotics Anonymous',
    'Outpatient Counseling',
    'Rehab',
    'Sober Living Homes',
    'Substance Abuse Treatment',
  ],
  spanish: [
    'Alcoholicos anonimos',
    'Asesoramiento para pacientes ambulatorios',
    'Asesoramiento sobre drogas y alcohol',
    'Centros de desintoxicación',
    'Crystal Meth Anónimo',
    'DUI',
    'Narcóticos Anónimos',
    'Rehabilitación',
    'Servicios de adicción',
    'Tratamiento por abuso de sustancias',
    'Viviendas sobrias',
  ],
}
export const cityCopy = [
  'Santa Barbara',
  'Santa Maria',
  'Lompoc',
  'Carpinteria',
  'Guadalupe',
  'Goleta',
  'Buellton',
  'Orcutt',
  'Santa Ynez',
  'Solvang',
]
