services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=thrive
      - POSTGRES_PASSWORD=sbc
    ports:
      - 5432:5432
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/docker_pg_init.sql
      - ./data:/mnt/data
